### ISSUE TITLE
成功的定义

### ISSUE THREAD

**Issue by dsun-da** [weining-da/featureboss#1]

**Comment by dsun-da** [comment]
Baby step 1: Can we describe the ideal workflow when we have all the tools?

**Comment by weining-da** [comment]
I'm speaking for myself. 
I want:
- a tool to verify whether the func-test is in-sync with the epic
- (if it is not) a tool to update it
- a tool to enforce formatting of the .feature files; and it is consistent cross platform;

**Comment by weining-da** [comment]
@shineli-da WDYT?

**Comment by weining-da** [comment]
in addition, I want to be able to judge the complexity of the func-test much like calculating the cyclomatic complexity: https://en.wikipedia.org/wiki/Cyclomatic_complexity

but it is not a focus for the immediate goal

**Comment by shineli-da** [comment]
Who's the target user? Product? 
I have no idea how product works when they are working on a Func test. Anyone has seen it? and can describe their workflow? If not, I think we need to talk to a product person first. (user interview)

**Comment by shineli-da** [comment]
If we are talking about devs, my problems only comes when a func test fails:
- a scenario that includes many messages other than the one my ticket is related to leaves me confused. Without any comments from product, it's time consuming for me to figure out what they are there for. 
- it's not easy for me to draw a conclusion that a variable or an assertion is wrong. I need to be extra careful that I have done 100% what the story tells me to do to call out a problem

>  tool to verify whether the func-test is in-sync with the epic

@weining-da For missed ACs, for me it's easy to spot. is there anything else you are referring to?

**Comment by weining-da** [comment]
product users can benefit from it but no, they are not the primary user;
agree with the above two pain points;

> For missed ACs, for me it's easy to spot. is there anything else you are referring to?

it maybe an isolated case, but it happens to me a few times that an ssp parameter is deliberately set to null in the "example" table (just to get it pass on CI) but obviously it contradicts to the client requirements;
it's not immediately noticeable unless the dev or the product people has months of experience in that area (which makes them a dependency in some case, but that's a different story).
so long idea short, I really want this kind of "yeah I know it's wrong because I know it" becomes "yeah I know it's wrong because the tool tells so".....ha

**Comment by shineli-da** [comment]
So your pain is overlapping with my second point. I think we can start there.

**Comment by weining-da** [comment]
nice

I just played around with some ideas last night - I wanted to make a quick and dirty web crawler so that I could extract the stories from the epic page in plain text, but realized that the JIRA epic page is dynamic so this crawler won't work....

**Comment by shineli-da** [comment]
dynamic depends on what?

**Comment by weining-da** [comment]
it's a dynamically rendered page, meaning that the javascripts won't be called by the normal html-crawling mechanism;

the only option (which is quite difficult) is to use something like splash or headless-chromium, that is basically a browser running as a service. I'd have to pass the page url to this background browser and get the resulting rendered page out....

because we use SSO and other security measures, this is close to impossible

**Comment by shineli-da** [comment]
I'm sure this is how atlassian e2e test their sso :D

**Comment by weining-da** [comment]
on the another hand I had some small success with feature file automation:

- gherkin parser generator is solid, easy to use and has pretty good performance (see below); there are js, py, haskell bindings for it
- we can program the parser to extract any information we want in a structural way, such as extracting the rows from the "Examples" table
- from there we would do some quick analysis and determine what actions to take 
- the parser also provides the token positions in the feature file, meaning that we can also modify the feature file based on the analysis - for instance, we can tag/untag multiple scenarios or add/remove multiple rows in the Examples table

here is the repo for the bindings:
https://github.com/cucumber/gherkin-python
https://github.com/cucumber/gherkin-javascript
https://github.com/sakari/haskell-gherkin

benchmark:
it took 1.3s to parse all the feature files using the python binding

**Comment by shineli-da** [comment]
Do you have an overview architecture in mind? might as well just to spit that out here?

**Comment by weining-da** [comment]
oh man... architecture talk... 

I think I still need to convince myself that this is going to work, hahaha 

the biggest question mark is still, how feasible it is to automatically dumping/crawling the confluence page (the epic page); if we don't have the data source then it's hard to make use of the downstream tooling in an efficient way. 

but regardless of this, it is probably a good exercise to try and write a handy feature/gherkin processor in Haskell

the gist of it might look like this:

- given the AST generated by the gherkin parser (or we can even try to write our own parser using attoparsec)
- use a recursive algorithm to extract the Scenario from the AST
- transform it into something of our interests, for example, it might spit out some DAML code skeletons

**Comment by shineli-da** [comment]
Let's assume we can get the data from the epic page. 
On a high level, my understanding is that we're trying to compare a set of attributes from the above data to the attributes extracted from func test. is this right?
In `mtl` sense(not saying we should use `mtl`), 
```Haskell
genSourceData :: (MonadExcept m, MonadIO m, MonadReader Config m) => m SourceData
genTestData :: (MonadExcept m, MonadIO m, MonadReader Config m) => m TestData
compare :: (MonadExcept m, MonadIO m) => SourceData -> TestData -> m ComparisonResult
program = do
  s <- genSourceData
  t <- genTestData
  result <- compare s t
  -- what we do with the result here?
```
Is above what we want? and what we do after getting the result of comparison?

**Comment by weining-da** [comment]
> we're trying to compare a set of attributes from the above data to the attributes extracted from func test. is this right?

yep, spot on

> what we do with the result here?

there are two broad directions:
one is, we simply output a json (or yaml) summary of the comparison, so that we can chain other program(s) that may consume the summary - I think the panda guys are doing something similar, sending the generated summary to google cloud platform

another is, we can define our own type(s) and a mini framework, so that it becomes easier when we need to do additional development later on, such as code-generation and linting

```haskell
program = do
  s <- genSourceData
  t <- genTestData
  result <- compare s t
  -- to external
  _ <- toJson result
  -- to internal processing chain
  _ <- codegen . lint . analyse $ result
```

**Comment by weining-da** [comment]
having said that, we probably don't need to worry about linting and code-generation, until we get more use cases

I think having a plain, readable message, that points to the issues in the feature files, like missing test cases etc. is more than helpful.... at least for me

**Comment by shineli-da** [comment]
> I think the panda guys are doing something similar, sending the generated summary to google cloud platform

what's this `generated summary` you are talking about?

**Comment by weining-da** [comment]
They run those load tests in the vdaml environment, that generates a series of trade sheets - similar to the feature file. They are written in a dsl I'm not familiar with. They guy who wrote it had left.
They then run a tool to ingest the trade sheets and remove most of the noise, then generate a json file that describe the throughput of the trades.

**Comment by weining-da** [comment]
I had a chat with Edward Newman (head of security) this morning and got some advice.
- running web crawler on ASX-facing JIRA/Confluence pages is discouraged as it (may) violate the ISO27K and the agreement with ASX
- on the other hand, wrangling those .feature files in the repository is totally fine, as long as the result is consumed completely in-house
